top_srcdir   = /home/cs408_team3/httpd-2.4.23
top_builddir = /home/cs408_team3/httpd-2.4.23
srcdir       = /home/cs408_team3/httpd-2.4.23/modules/echo
builddir     = /home/cs408_team3/httpd-2.4.23/modules/echo
VPATH        = /home/cs408_team3/httpd-2.4.23/modules/echo

include $(top_srcdir)/build/special.mk

