top_srcdir   = /home/cs408_team3/httpd-2.4.23
top_builddir = /home/cs408_team3/httpd-2.4.23
srcdir       = /home/cs408_team3/httpd-2.4.23/modules/arch/unix
builddir     = /home/cs408_team3/httpd-2.4.23/modules/arch/unix
VPATH        = /home/cs408_team3/httpd-2.4.23/modules/arch/unix

include $(top_srcdir)/build/special.mk

