top_srcdir   = /home/cs408_team3/httpd-2.4.23
top_builddir = /home/cs408_team3/httpd-2.4.23
srcdir       = /home/cs408_team3/httpd-2.4.23/srclib
builddir     = /home/cs408_team3/httpd-2.4.23/srclib
VPATH        = /home/cs408_team3/httpd-2.4.23/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
