top_srcdir   = /home/cs408_team3/httpd-2.4.23
top_builddir = /home/cs408_team3/httpd-2.4.23
srcdir       = /home/cs408_team3/httpd-2.4.23/server/mpm/worker
builddir     = /home/cs408_team3/httpd-2.4.23/server/mpm/worker
VPATH        = /home/cs408_team3/httpd-2.4.23/server/mpm/worker

include $(top_srcdir)/build/special.mk
