top_srcdir   = /home/cs408_team3/httpd-2.4.23
top_builddir = /home/cs408_team3/httpd-2.4.23
srcdir       = /home/cs408_team3/httpd-2.4.23/modules/filters
builddir     = /home/cs408_team3/httpd-2.4.23/modules/filters
VPATH        = /home/cs408_team3/httpd-2.4.23/modules/filters

include $(top_srcdir)/build/special.mk

