top_srcdir   = /home/cs408_team3/httpd-2.4.23
top_builddir = /home/cs408_team3/httpd-2.4.23
srcdir       = /home/cs408_team3/httpd-2.4.23/modules/dav/main
builddir     = /home/cs408_team3/httpd-2.4.23/modules/dav/main
VPATH        = /home/cs408_team3/httpd-2.4.23/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
